In [1]:
import torch

In [41]:
from torch import float32
a = torch.tensor([[ 0.2927,  0.3856, -0.8933]])
a

tensor([[ 0.2927,  0.3856, -0.8933]])

In [29]:
a[0,:2]

tensor([0.2927, 0.3856])

In [44]:
b = torch.max(a, 1)
b

torch.return_types.max(
values=tensor([0.3856]),
indices=tensor([1]))

In [45]:
b[1]

tensor([1])

In [51]:
b[1].data.numpy()[0]

1